
CREATE TABLE T_USUARIO (
	ID_USUARIO	SERIAL NOT NULL PRIMARY KEY,
	USUARIO		TEXT NOT NULL UNIQUE,
	PASSWORD	TEXT NOT NULL,
	NOMBRE		TEXT NOT NULL,
	APELLIDO	TEXT NOT NULL,
	MAIL		TEXT NOT NULL UNIQUE,
	ACTIVO		BOOLEAN DEFAULT TRUE
);

CREATE TABLE T_VEHICULOS (
	ID_VEHICULO	SERIAL PRIMARY KEY,
	MARCA		TEXT NOT NULL,
	REFERENCIA	TEXT NOT NULL,
	MODELO		INT2 NOT NULL,
	PLACA		TEXT NOT NULL UNIQUE,
	COLOR		TEXT NOT NULL,
	ACTIVO		BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE T_CONDUCTOR (
	ID_CONDUCTOR	SERIAL NOT NULL PRIMARY KEY,
	NOMBRE		TEXT NOT NULL,
	APELLIDO	TEXT NOT NULL,
	NRO_DOCUMENTO	INT8 NOT NULL,
	NRO_CUENTA	TEXT NOT NULL,
	ACTIVO		BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE T_VEHICULO_X_CONDUCTOR (
	ID_VEHICULO_CONDUCTOR	SERIAL NOT NULL PRIMARY KEY,
	ID_VEHICULO	INT8 NOT NULL REFERENCES T_VEHICULOS (ID_VEHICULO),
	ID_CONDUCTOR	INT8 NOT NULL REFERENCES T_CONDUCTOR (ID_CONDUCTOR),
	FECHA		TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE T_METODO_PAGO (
	ID_METODO_PAGO	SERIAL NOT NULL PRIMARY KEY,
	METODO_PAGO	TEXT NOT NULL
);

CREATE TABLE T_BONOS_X_USUARIO (
	ID_BONO_USUARIO		SERIAL NOT NULL PRIMARY KEY,
	ID_USUARIO		INT8 NOT NULL REFERENCES T_USUARIO(ID_USUARIO),
	VALOR			NUMERIC,
	FECHA_CADUCIDAD		DATE NOT NULL,
	NOMBRE_CAMPANIA		TEXT NOT NULL,
	FECHA_USO		TIMESTAMP
);

CREATE TABLE T_VIAJES (
	ID_VIAJE		SERIAL PRIMARY KEY NOT NULL,
	ID_USUARIO		INT8 NOT NULL REFERENCES T_USUARIO(ID_USUARIO),
	LAT_ORIGEN		NUMERIC NOT NULL,
	LON_ORIGEN		NUMERIC NOT NULL,
	FECHA			TIMESTAMP NOT NULL DEFAULT NOW(),
	LAT_DESTINO		NUMERIC NOT NULL,
	LON_DESTINO		NUMERIC NOT NULL,
	ID_VEHICULO_CONDUCTOR 	INT8 NOT NULL REFERENCES T_VEHICULO_X_CONDUCTOR(ID_VEHICULO_CONDUCTOR),
	ID_METODO_PAGO		INT8 NOT NULL REFERENCES T_METODO_PAGO(ID_METODO_PAGO),
	VALOR_PAGAR		NUMERIC NOT NULL
);

CREATE TABLE T_DESTINOS_FAVORITOS_X_USUARIO (
	ID_DESTINO_FAVORITO	SERIAL NOT NULL PRIMARY KEY,
	ID_USUARIO		INT8 NOT NULL REFERENCES T_USUARIO(ID_USUARIO),
	LATITUD			NUMERIC NOT NULL,
	LONGITUD		NUMERIC NOT NULL,
	ALIAS			TEXT NOT NULL
);